'use client';
import { useEffect, useState } from 'react';

type Product = { id: string; name: string; price: number; size: string; color: string; imageUrl: string; description: string };
type CartItem = Product & { quantity: number };

const methods = [['RAZORPAY', 'UPI / Cards / Net banking / Wallets'], ['COD', 'Cash on delivery']];
export default function Storefront() {
  const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartItem[]>([]); const [size, setSize] = useState('all'); const [color, setColor] = useState('all'); const [maxPrice, setMaxPrice] = useState(4200); const [auth, setAuth] = useState(false); const [register, setRegister] = useState(false); const [message, setMessage] = useState(''); const [payment, setPayment] = useState('RAZORPAY');
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', address: '' });
  const load = async () => { const response = await fetch(`/api/products?maxPrice=${maxPrice}&size=${size}&color=${color}`); setProducts(await response.json()); };
  useEffect(() => { load(); }, [maxPrice, size, color]);
  const add = (product: Product) => setCart((items) => { const found = items.find((i) => i.id === product.id); return found ? items.map((i) => i.id === product.id ? { ...i, quantity: i.quantity + 1 } : i) : [...items, { ...product, quantity: 1 }]; });
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const submitAuth = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(register ? '/api/auth/register' : '/api/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); setMessage(data.error || 'You are signed in.'); if (response.ok) setAuth(false); };
  const checkout = async () => { if (!cart.length) return setMessage('Add a frame to your cart first.'); const response = await fetch('/api/orders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ items: cart.map((i) => ({ productId: i.id, quantity: i.quantity })), paymentMethod: payment, shippingName: form.name || 'Customer', shippingPhone: form.phone || '+91 91013 87479', shippingAddress: form.address || 'To be confirmed on WhatsApp' }) }); const data = await response.json(); setMessage(data.error || `${data.message} Order ${data.orderId}`); if (response.ok) setCart([]); };
  return <><header className="nav"><a className="logo" href="#home"><span>AC</span><b>Arnab Crafts</b></a><nav><a href="#shop">Shop</a><a href="#about">About</a><a href="#contact">Contact</a><button onClick={() => setAuth(true)}>Register / Login</button></nav><a className="cart" href="#cart">Cart ({cart.reduce((s, i) => s + i.quantity, 0)})</a></header>
    <main id="home"><section className="hero"><div><p className="eyebrow">Custom handmade keepsakes</p><h1>Your memories,<br /><em>beautifully framed.</em></h1><p>Customized photo frames from ₹149, made for anniversaries, celebrations, gifts, and everyday moments.</p><a className="primary" href="#shop">Explore collection</a><a className="text-link" href="https://wa.me/919101387479" target="_blank">WhatsApp us ↗</a></div><img src="https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=85" alt="Beautiful home with framed art" /></section>
    <section className="shop" id="shop"><div className="section-title"><div><p className="eyebrow">The collection</p><h2>Made for your story</h2></div><p>A4 to large-size frames, customized by Arnab Crafts.</p></div><div className="filters"><label>Price: up to ₹{maxPrice}<input type="range" min="149" max="4200" value={maxPrice} onChange={(e) => setMaxPrice(Number(e.target.value))} /></label><label>Size<select value={size} onChange={(e) => setSize(e.target.value)}><option value="all">All sizes</option><option value="A4">A4</option><option value="A3">A3</option><option value="A2">A2</option><option value="LARGE">Large</option></select></label><label>Frame color<select value={color} onChange={(e) => setColor(e.target.value)}><option value="all">All colors</option><option value="WALNUT">Walnut</option><option value="BLACK">Black</option><option value="WHITE">White</option><option value="GOLDEN">Golden</option><option value="NATURAL_OAK">Natural oak</option><option value="ROSEWOOD">Rosewood</option></select></label></div><div className="grid">{products.map((p) => <article className="card" key={p.id}><img src={p.imageUrl} alt={p.name} /><div className="card-body"><div className="meta">{p.size.replace('_', ' ')} · {p.color.replace('_', ' ')}</div><h3>{p.name}</h3><p>{p.description}</p><div className="card-bottom"><strong>₹{p.price}</strong><button onClick={() => add(p)}>Add to cart</button></div></div></article>)}</div></section>
    <section className="story" id="about"><div><p className="eyebrow">The Arnab Crafts promise</p><h2>Handmade details.<br />Heartfelt gifting.</h2></div><p>We turn your favourite photographs into tactile, lasting pieces for your walls. Choose your frame color and size, then send your photo and customization details over WhatsApp after ordering.</p></section>
    <section className="checkout" id="cart"><div><p className="eyebrow">Your order</p><h2>Ready to make it yours?</h2>{cart.length ? cart.map((i) => <div className="line" key={i.id}><span>{i.name} × {i.quantity}</span><b>₹{i.price * i.quantity}</b></div>) : <p>Your cart is ready for a beautiful memory.</p>}<div className="total"><span>Total</span><b>₹{total}</b></div></div><div className="order-box"><h3>Checkout & payment</h3><p>UPI, credit/debit cards, net banking, wallets, and cash on delivery are supported. Online payments require the owner’s Razorpay merchant credentials.</p>{methods.map(([value, label]) => <label className="radio" key={value}><input type="radio" value={value} checked={payment === value} onChange={(e) => setPayment(e.target.value)} />{label}</label>)}<input placeholder="Your phone number" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><textarea placeholder="Delivery address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /><button className="primary wide" onClick={checkout}>Place order</button><a className="whatsapp" href="https://wa.me/919101387479" target="_blank">Need help? WhatsApp +91 91013 87479</a></div></section>
    <section className="contact" id="contact"><p className="eyebrow">Let’s create something special</p><h2>Have a custom idea?</h2><p>Call or WhatsApp the owner for custom designs, bulk gifts, and photo submission.</p><a className="primary" href="tel:+919101387479">+91 91013 87479</a></section></main>
    {auth && <div className="modal"><form onSubmit={submitAuth} className="auth"><button type="button" className="close" onClick={() => setAuth(false)}>×</button><p className="eyebrow">Customer account</p><h2>{register ? 'Create account' : 'Welcome back'}</h2>{register && <input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />}<input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />{register && <input required placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} />}<input required type="password" minLength={8} placeholder="Password (8+ characters)" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button className="primary wide">{register ? 'Register' : 'Login'}</button><button type="button" className="switch" onClick={() => setRegister(!register)}>{register ? 'Already registered? Login' : 'New customer? Register'}</button>{message && <p className="notice">{message}</p>}</form></div>}
    {message && !auth && <div className="toast">{message}</div>}</>;
}
